pipeline {
    agent none
     environment {
      version = "${params.version}"
       workspace = "${env.WORKSPACE}"
        artifact_path = "target/my-app-${version}-RELEASES.jar"
     }
     stages {
        stage('Build') {
           agent {
        label "test" }
     tools {
        git 'Default' 
     }
          steps {
            dir("test-pipeline"){
            sh "mvn versions:set -DnewVersion=${version}-RELEASES"
            sh "mvn -Dmaven.test.failure.ignore clean package"
        }
      }
    }
        stage('Deploy') {
            agent {
        label "test" }
        tools {
        git 'Default' 
     }
          steps {
           dir("test-pipeline"){
                  nexusPublisher nexusInstanceId: 'nexus', nexusRepositoryId: 'maven-releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: "${artifact_path}"]], mavenCoordinate: [artifactId: "my-app", groupId: 'nexus.com', packaging: 'jar', version: "${version}-RELEASES"]]]
          }           
          }
        }
        }
}