pipeline {
    agent any 
     environment {
       version = "${env.BUILD_NUMBER}"
       workspace = "${env.WORKSPACE}"
     }
     stages {
        stage('Build') {
          steps {
            dir("test-pipeline"){
            sh "mvn versions:set -DnewVersion=1.0.${version}-SNAPSHOT"
            sh "mvn -Dmaven.test.failure.ignore clean package"
        }
      }
    }
       stage('Deploy') {
         steps {
           dir("test-pipeline"){
            nexusPublisher nexusInstanceId: 'nexus', nexusRepositoryId: 'maven-snapshots', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: "target/my-app-1.0.${version}-SNAPSHOT.jar"]], mavenCoordinate: [artifactId: "my-app", groupId: "com.mycompany.app", packaging: 'jar', version: "1.0.${version}-SNAPSHOT"]]]
           }
         }
       }
  }
}