pipeline {
    agent any 
     environment {
      version = "${params.version}"
       workspace = "${env.WORKSPACE}"
        artifact_path = "target/my-app-${version}-RELEASES.jar"
     }
     properties([[$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false], parameters([string(defaultValue: '', description: 'Version of build', name: 'version', trim: false)])])
     stages {
        stage('Build') {
          steps {
            dir("test-pipeline"){
            sh "mvn versions:set -DnewVersion=${version}-RELEASES"
            sh "mvn -Dmaven.test.failure.ignore clean package"
        }
      }
    }
        stage('Deploy'){
          steps {
           dir("test-pipeline"){
                  nexusPublisher nexusInstanceId: 'nexus', nexusRepositoryId: 'maven-releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: "${artifact_path}"]], mavenCoordinate: [artifactId: "my-app", groupId: 'nexus.com', packaging: 'jar', version: "${version}-RELEASES"]]]
          }           
          }
        }
     }
}  